name: 701-project
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3  # Remove or adjust version if not using CUDA
  - pip:
    - transformers
    - pennylane==0.29
    - huggingface_hub==0.7.0
    - typing-extensions==4.1.1
    - datasets
