name: 701-project
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3  # Remove or adjust version if not using CUDA
  - pip:
    - transformers
    - pennylane
    - huggingface_hub
    - typing-extensions
    - datasets
    - sentence_transformers
    # If using 'lightning.gpu', need to install https://pennylane.ai/install#high-performance-computing-and-gpus
